# 数据源集合
dataSources:
  link_ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/link_0?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zq2892294059

  link_ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/link_1?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zq2892294059

  link_stats_ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/link_stats_0?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zq2892294059

  link_stats_ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/link_stats_1?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zq2892294059
rules:
  - !SHARDING
    tables:
      t_link:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: link_ds_${0..1}.t_link_${0..15}
        #定义分库规则，即数据应该路由到哪个数据库
        databaseStrategy:
          #单分片键分库
          standard:
            #指定分库依据的字段名
            shardingColumn: gid
            #指定分库算法
            shardingAlgorithmName: link_database_hash_mod
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: gid
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: link_table_hash_mod
      t_link_goto:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: link_ds_${0..1}.t_link_goto_${0..15}
        #定义分库规则，即数据应该路由到哪个数据库
        databaseStrategy:
          #单分片键分库
          standard:
            #指定分库依据的字段名
            shardingColumn: gid
            #指定分库算法
            shardingAlgorithmName: link_database_hash_mod
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: full_short_url
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: link_goto_table_hash_mod
      t_link_access_stats:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: link_stats_ds_${0..1}.t_link_access_stats_${0..15}
        #定义分库规则，即数据应该路由到哪个数据库
        databaseStrategy:
          #单分片键分库
          standard:
            #指定分库依据的字段名
            shardingColumn: gid
            #指定分库算法
            shardingAlgorithmName: link_stats_database_hash_mod
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: gid
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: t_link_access_stats_table_hash_mod
    # 分片算法
    shardingAlgorithms:
      # 短链接数据库分片算法
      link_database_hash_mod:
        # 根据分片键 Hash 分片
        type: HASH_MOD
        # 分片数量
        props:
          sharding-count: 2
      # 短链接监控数据库分片算法
      link_stats_database_hash_mod:
        # 根据分片键 Hash 分片
        type: HASH_MOD
        # 分片数量
        props:
          sharding-count: 2
      # 数据表分片算法
      link_table_hash_mod:
        # 根据分片键 Hash 分片
        type: HASH_MOD
        # 分片数量
        props:
          sharding-count: 16
      # 数据表分片算法
      link_goto_table_hash_mod:
        # 根据分片键 Hash 分片
        type: HASH_MOD
        # 分片数量
        props:
          sharding-count: 16
      # 数据表分片算法
      t_link_access_stats_table_hash_mod:
        # 根据分片键 Hash 分片
        type: HASH_MOD
        # 分片数量
        props:
          sharding-count: 16
# 展现逻辑 SQL & 真实 SQL
props:
  sql-show: true